<meta name="author" content="Ruiz Olivier">
		        <!--[if lt IE 9]>
                <script src="../js/html5shiv.js"></script>
                <![endif]-->
		<link rel="stylesheet" href="../css/css_antworld.css"/>

<meta name="description" content="An Icon Font Generated By IcoMoon.io"><meta name="viewport" content="width=device-width, initial-scale=1">
<!--[if lt IE 8]><!--><link rel="stylesheet" href="ie7/ie7.css"><!--<![endif]-->
<?php include("../php/favicon.php"); ?><?php include("../php/scripts.php") ?>
<script src="../js/prefixfree.js" type="text/javascript"></script>
    </head>